export default defineAppConfig({
  pages: [
    'pages/login/index',
    'pages/onboarding/index',
    'pages/home/index',
    'pages/catalog/index',
    'pages/practice/index',
    'pages/practice/session',
    'pages/practice/result',
    'pages/practice/config',
    'pages/wrong/analysis',
    'pages/study/plan',
    'pages/study/daily',
    'pages/study/checkin',
    'pages/learn/report',
    'pages/learn/notes',
    'pages/wrong/index',
    'pages/favorite/index',
    'pages/progress/index',
    'pages/profile/index',
    'pages/feedback/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#ffffff',
    navigationBarTitleText: '刷题本',
    navigationBarTextStyle: 'black',
  },
  tabBar: {
    color: '#9CA3AF',
    selectedColor: '#2563EB',
    backgroundColor: '#ffffff',
    borderStyle: 'white',
    list: [
      { pagePath: 'pages/home/index',      text: '首页' },
      { pagePath: 'pages/catalog/index',  text: '题库' },
      { pagePath: 'pages/practice/index', text: '练习' },
      { pagePath: 'pages/profile/index',  text: '我的' },
    ],
  },
});
