#!/usr/bin/env bash
# scripts/local_ip.sh — 输出本机可被外部访问的 IPv4，并把结果写入配置文件。
#
# 优先级（带自检，避免被 NAT 出口 IP 误导）：
#   1. 真公网 IPv4：curl https://ifconfig.me + 自检本机能否到达该 IP（绕过代理）。
#      hairpin NAT 不支持的情况下会超时，自动降级。
#   2. 局域网 IPv4：macOS 用 ipconfig getifaddr en1/en0/en2（活跃网卡优先）；
#      Linux 用 hostname -I。
#   3. 都失败时 fallback 127.0.0.1。
#
# 用法：
#   ./scripts/local_ip.sh                       # 只输出 IP（公网优先）
#   ./scripts/local_ip.sh url <port>            # 输出 http://<ip>:<port>
#   ./scripts/local_ip.sh reachable <port>      # 拿公网 IP 时顺便 curl 一下验证可达性
#   ./scripts/local_ip.sh write <root_dir>      # 探测后写入 miniprogram/.env.local + admin-web/.env.local
#
# 在 Makefile 里这样用：
#   IP  := $(shell bash scripts/local_ip.sh)
#   URL := $(shell bash scripts/local_ip.sh url 8000)
#   WRITE := $(shell bash scripts/local_ip.sh write $(ROOT_DIR))

set -u

mode="ip"
port=""
root_dir=""
if [ "${1:-}" = "url" ]; then
  mode="url"
  port="${2:-}"
elif [ "${1:-}" = "reachable" ]; then
  mode="reachable"
  port="${2:-}"
elif [ "${1:-}" = "write" ]; then
  mode="write"
  root_dir="${2:-$(pwd)}"
fi

is_public_ipv4() {
  local ip="$1"
  [[ "$ip" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]] || return 1
  case "$ip" in
    10.*|192.168.*|172.1[6-9].*|172.2[0-9].*|172.3[0-1].*) return 1 ;;
    0.*|127.*|169.254.*|224.*|240.*) return 1 ;;
  esac
  return 0
}

is_private_ipv4() {
  local ip="$1"
  [[ "$ip" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]] || return 1
  case "$ip" in
    10.*|192.168.*|172.1[6-9].*|172.2[0-9].*|172.3[0-1].*) return 0 ;;
    127.*) return 0 ;;
  esac
  return 1
}

probe_lan_ip() {
  local cand
  if command -v ipconfig >/dev/null 2>&1; then
    # macOS：先查活跃 Wi-Fi/以太网接口（en1 是当前 Wi-Fi，en0 是以太网）
    for iface in en1 en0 en2 en3 bridge100; do
      cand=$(ipconfig getifaddr "$iface" 2>/dev/null || true)
      if is_private_ipv4 "$cand"; then echo "$cand"; return 0; fi
    done
  elif command -v hostname >/dev/null 2>&1; then
    cand=$(hostname -I 2>/dev/null | awk '{print $1}')
    if is_private_ipv4 "$cand"; then echo "$cand"; return 0; fi
  fi
  # 兜底：从 ifconfig 输出里捞第一个非 127 的 IPv4
  if command -v ifconfig >/dev/null 2>&1; then
    cand=$(ifconfig 2>/dev/null | awk '/inet /{print $2}' | grep -v '127.0.0.1' | head -1)
    if is_private_ipv4 "$cand"; then echo "$cand"; return 0; fi
  fi
  return 1
}

# 探测 + 自检降级，返回形如 http://<ip>:<port> 的 URL
probe_url() {
  local p="${1:-}"
  # 1) 公网 IP + 自检
  if command -v curl >/dev/null 2>&1; then
    local pub
    pub=$(curl -sS --max-time 4 https://ifconfig.me 2>/dev/null || true)
    if is_public_ipv4 "$pub"; then
      if [ -n "$p" ]; then
        # 自检：本机是否能到达这个 IP 的目标端口（绕过代理，hairpin 受限会超时）
        if curl -sS --noproxy '*' --max-time 2 --connect-timeout 2 \
             -o /dev/null "http://${pub}:${p}/api/v1/health" 2>/dev/null; then
          echo "http://${pub}:${p}"
          return 0
        fi
        # hairpin NAT 受限，降级 LAN
        local lan
        lan=$(probe_lan_ip || true)
        if [ -n "$lan" ]; then
          echo "http://${lan}:${p}"
          return 0
        fi
        echo "http://127.0.0.1:${p}"
        return 0
      fi
      echo "$pub"
      return 0
    fi
  fi
  # 2) 走 LAN
  local lan
  lan=$(probe_lan_ip || true)
  if [ -n "$lan" ]; then
    if [ -n "$p" ]; then echo "http://${lan}:${p}"; else echo "$lan"; fi
    return 0
  fi
  # 3) fallback
  if [ -n "$p" ]; then echo "http://127.0.0.1:${p}"; else echo "127.0.0.1"; fi
  return 0
}

# 写入 .env.local：探测当前 IP，落到两个前端项目的本地配置文件
do_write() {
  local backend_url ts mp_dir admin_dir
  # 注意：admin 的 vite proxy 把 /api /static 反代到 backend，所以 admin-web 写的也是 backend URL
  backend_url=$(probe_url 8000)
  ts=$(date '+%Y-%m-%d %H:%M:%S %z')

  mp_dir="${root_dir}/miniprogram"
  admin_dir="${root_dir}/admin-web"

  mkdir -p "$mp_dir" "$admin_dir"

  cat > "${mp_dir}/.env.local" <<EOF
# Generated by scripts/local_ip.sh at ${ts}
# 公网 IP 优先，hairpin NAT 不通时自动降级 LAN。
# 如需手动指定，覆盖下面两行即可；保持本文件存在即可不再探测。
TARO_APP_API_BASE=${backend_url}/api/v1
EOF

  cat > "${admin_dir}/.env.local" <<EOF
# Generated by scripts/local_ip.sh at ${ts}
# 公网 IP 优先，hairpin NAT 不通时自动降级 LAN。
# 如需手动指定，覆盖下面一行即可。
# 注意：这是 vite 反代的目标（backend），不是 admin 自己。
VITE_API_TARGET=${backend_url}
EOF

  echo "[local_ip] miniprogram/.env.local: TARO_APP_API_BASE=${backend_url}/api/v1"
  echo "[local_ip] admin-web/.env.local:   VITE_API_TARGET=${backend_url}"
}

case "$mode" in
  ip|reachable|url)
    probe_url "$port"
    ;;
  write)
    do_write
    ;;
esac